using System;
using System.IO;
using System.Linq;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tiro.Health.FormFiller.WebView2.Tests
{
    [TestClass]
    public class TestEmbeddedWebAssets
    {
        // Logical resource names must match the <LogicalName> entries in
        // Tiro.Health.FormFiller.WebView2.csproj. Renaming a WebAsset file
        // without updating the project file (or vice-versa) silently breaks
        // BridgeJs.cs and DefaultWebContent.cs at runtime — this test fails
        // build-time instead.
        [DataTestMethod]
        [DataRow("Tiro.Health.FormFiller.WebView2.WebAssets.index.html")]
        [DataRow("Tiro.Health.FormFiller.WebView2.WebAssets.tiro-swm-bridge.js")]
        [DataRow("Tiro.Health.FormFiller.WebView2.WebAssets.tiro-web-sdk.iife.js")]
        [DataRow("Tiro.Health.FormFiller.WebView2.WebAssets.web-sdk.version.json")]
        public void WebAsset_IsEmbeddedAndNonEmpty(string resourceName)
        {
            var asm = typeof(TiroFormViewerState).Assembly;

            using var stream = asm.GetManifestResourceStream(resourceName);

            Assert.IsNotNull(stream, $"Resource '{resourceName}' was not embedded in {asm.GetName().Name}.");
            Assert.IsTrue(stream.Length > 0, $"Resource '{resourceName}' is empty.");
        }

        // The shipped index.html is a placeholder: it carries a banner
        // identifying itself as the library default plus a "Copy starter
        // template" button. Removing either silently regresses issue #7's
        // discovery UX, so we pin the markers here.
        [TestMethod]
        public void IndexHtml_ContainsPlaceholderBannerMarkers()
        {
            var html = ReadEmbeddedString("Tiro.Health.FormFiller.WebView2.WebAssets.index.html");

            StringAssert.Contains(html, "id=\"sample-banner\"");
            StringAssert.Contains(html, "id=\"copy-template-btn\"");
            StringAssert.Contains(html, "data-sample-only");
        }

        // Issue #6: endpoints are configured from the .NET host via
        // TiroFormViewer.SdcEndpointAddress / DataEndpointAddress, not hardcoded
        // in the page. Pinning this keeps a future "small fix" from re-adding
        // a baked-in URL that would silently override host configuration.
        [TestMethod]
        public void IndexHtml_DoesNotHardcodeEndpointAttributes()
        {
            var html = ReadEmbeddedString("Tiro.Health.FormFiller.WebView2.WebAssets.index.html");

            Assert.IsFalse(html.Contains("sdc-endpoint-address="),
                "index.html must not hardcode sdc-endpoint-address; let the .NET host configure it.");
            Assert.IsFalse(html.Contains("data-endpoint-address="),
                "index.html must not hardcode data-endpoint-address; let the .NET host configure it.");
        }

        // GH-60: the harness embeds and injects the web-sdk itself; a page-loaded
        // copy would collide with it. Guards against the script tag creeping back.
        [TestMethod]
        public void IndexHtml_HasNoWebSdkScriptTag()
        {
            var html = ReadEmbeddedString("Tiro.Health.FormFiller.WebView2.WebAssets.index.html");

            Assert.IsFalse(html.Contains("cdn.tiro.health"),
                "index.html must not load the web-sdk from the CDN; the bridge injects the embedded copy (GH-60).");
        }

        // The embedded version manifest is generated by build/web-sdk/copy-bundle.mjs
        // and must parse with a version (GH-61 asserts against it at handshake).
        [TestMethod]
        public void WebSdkVersionManifest_ParsesWithAVersion()
        {
            Assert.IsFalse(string.IsNullOrEmpty(WebSdkAssets.Version));
        }

        // The bridge reads its SDK URL from window.__tiroSdkUrl, which the host injects, and
        // falls back to the same virtual host. Both sides of that runtime boundary are
        // hardcoded, so pin them together.
        [TestMethod]
        public void Bridge_TakesItsSdkUrlFromTheHost_AndFallsBackToTheMappedVirtualHost()
        {
            var bridge = ReadEmbeddedString("Tiro.Health.FormFiller.WebView2.WebAssets.tiro-swm-bridge.js");

            StringAssert.Contains(bridge, "window.__tiroSdkUrl");
            StringAssert.Contains(bridge, $"https://{WebSdkAssets.VirtualHostName}/");
        }

        // The served file name carries the SDK version: the virtual host caches by URL, so a
        // constant name let WebView2 serve a previous release's bundle after an upgrade.
        [TestMethod]
        public void BundleUrl_CarriesTheEmbeddedSdkVersion()
        {
            StringAssert.Contains(WebSdkAssets.BundleUrl, WebSdkAssets.Version);
            StringAssert.StartsWith(WebSdkAssets.BundleUrl, $"https://{WebSdkAssets.VirtualHostName}/");
            StringAssert.EndsWith(WebSdkAssets.BundleUrl, ".iife.js");
        }

        // The URL the page fetches and the file the host publishes are derived separately;
        // if they ever disagree the SDK 404s at runtime and the form never renders.
        [TestMethod]
        public void BundleUrl_ResolvesToThePublishedFile()
        {
            Assert.AreEqual(WebSdkAssets.BundleFileName, new Uri(WebSdkAssets.BundleUrl).Segments.Last());
            Assert.IsTrue(File.Exists(Path.Combine(WebSdkAssets.FolderPath, WebSdkAssets.BundleFileName)),
                $"the bundle was not published as '{WebSdkAssets.BundleFileName}' in {WebSdkAssets.FolderPath}");
        }

        // The bridge handles the protocol's sdc.configure message: it stashes the
        // payload and applies payload.configuration.sdcServer / payload.dataServer
        // to the <tiro-form-filler> element's endpoint attributes right before the
        // form-filler initializes (i.e. when the `questionnaire` attribute is set
        // from the sdc.displayQuestionnaire handler). The .NET host's
        // TiroFormViewer.SdcEndpointAddress / DataEndpointAddress pipeline drives
        // this by calling SendSdcConfigureAsync after handshake.
        // Pinning the contract here keeps the JS and C# halves from drifting apart.
        [TestMethod]
        public void BridgeJs_HandlesSdcConfigureMessage()
        {
            var js = ReadEmbeddedString("Tiro.Health.FormFiller.WebView2.WebAssets.tiro-swm-bridge.js");

            StringAssert.Contains(js, "SmartWebMessaging.on(\"sdc.configure\"");
            StringAssert.Contains(js, "configuration.sdcServer");
            StringAssert.Contains(js, "dataServer");
            StringAssert.Contains(js, "sdc-endpoint-address");
            StringAssert.Contains(js, "data-endpoint-address");
            // The deprecated pre-injection path is gone; assert no regression.
            Assert.IsFalse(js.Contains("__tiroFormFillerConfig"),
                "Bridge must not read window.__tiroFormFillerConfig — endpoints come via sdc.configure now.");
        }

        private static string ReadEmbeddedString(string resourceName)
        {
            var asm = typeof(TiroFormViewerState).Assembly;
            using var stream = asm.GetManifestResourceStream(resourceName);
            Assert.IsNotNull(stream, $"Resource '{resourceName}' was not embedded.");
            using var reader = new StreamReader(stream);
            return reader.ReadToEnd();
        }
    }
}
